---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
    update_cache: yes

- name: Add NodeSource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Create application directory
  file:
    path: "{{ app_root }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Clone VueJS repository
  git:
    repo: "{{ repository_url }}"
    dest: "{{ app_root }}"
    version: "{{ git_branch | default('main') }}"
    force: true
  become_user: "{{ app_user }}"

- name: Install npm dependencies
  npm:
    path: "{{ app_root }}"
    state: present
  become_user: "{{ app_user }}"

- name: Create environment file
  template:
    src: env.j2
    dest: "{{ app_root }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0644'

- name: Build App
  ansible.builtin.shell: npm run build
  args:
    chdir: "{{ app_root }}"
