---
app_name: vue-app
app_user: www-data
app_group: www-data
app_root: /var/www/{{ app_name }}
nodejs_version: 20
domain_name: easysetup.fr
repository_url: https://github.com/maxime67/dofVue
git_branch: master
api_url: http://192.168.1.42:3000

#  CLEANUP VARS
cleanup_paths:
  - /tmp/*
  - /var/tmp/*
log_paths:
  - /var/log/*.log
  - /var/log/*.gz
services_to_stop:
  - apache
packages_to_remove:
  - nodejs
  - npm
  - apache