---
- name: Deploy VueJS Application
  hosts: all
  become: yes
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
  tasks:
    - import_playbook: cleanup.yml

  roles:
    - apache
    - vuejs